### ISSUE TITLE
Cannot locate configuration. Error while triggering with job.

### ISSUE THREAD

**Issue by bujiazhang** [stanfordmed/n3c-spark-exporter#12]
Hi, 
I am from University of Colorado, Colorado participated N3C submission and have been use this n3c-spark-exporter for a while. It saved a lot of our data extraction run time. 
For this week's run, I got error message: "Error while triggering with job, continuing with cleanup" from n3c_spark_extractor.log file. It says 409 Google Cloud Dataproc Agent reports job failure. 
Then I checked the log from GCS bucket, it shows cannot locate configuration. However, I was able to run the same job two weeks ago and there's no change been applied to the VM, virtual environment, and accounts. I have tried several times but got the same error messages. 

The details of the Dataproc log: 
`Using the default container image
Waiting for container log creation
PYSPARK_PYTHON=/opt/dataproc/conda/bin/python
Generating /home/spark/.pip/pip.conf
Configuring index-url as 'https://us-python.pkg.dev/artifact-registry-python-cache/virtual-python/simple/'
JAVA_HOME=/usr/lib/jvm/temurin-17-jdk-amd64
SPARK_EXTRA_CLASSPATH=
:: loading settings :: file = /etc/spark/conf/ivysettings.xml
24/09/18 17:25:48 WARN MetricsConfig: Cannot locate configuration: tried hadoop-metrics2-google-hadoop-file-system.properties,hadoop-metrics2.properties
Traceback (most recent call last):
  File "/var/dataproc/tmp/srvls-batch-3bf2bb83-8678-4484-ada7-cad245644345/spark_sql_batch.py", line 139, in <module>
    sys.exit(main())
             ^^^^^^
  File "/var/dataproc/tmp/srvls-batch-3bf2bb83-8678-4484-ada7-cad245644345/spark_sql_batch.py", line 135, in main
    runner = spark_sql_batch(args.batch_config, args.env_config)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/dataproc/tmp/srvls-batch-3bf2bb83-8678-4484-ada7-cad245644345/spark_sql_batch.py", line 45, in __init__
    self.run_spark_sql_manifest()
  File "/var/dataproc/tmp/srvls-batch-3bf2bb83-8678-4484-ada7-cad245644345/spark_sql_batch.py", line 107, in run_spark_sql_manifest
    .load()
     ^^^^^^
  File "/usr/lib/spark/python/lib/pyspark.zip/pyspark/sql/readwriter.py", line 314, in load
  File "/usr/lib/spark/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1322, in __call__
  File "/usr/lib/spark/python/lib/pyspark.zip/pyspark/errors/exceptions/captured.py", line 179, in deco
  File "/usr/lib/spark/python/lib/py4j-0.10.9.7-src.zip/py4j/protocol.py", line 326, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o87.load.
: java.util.ServiceConfigurationError: org.apache.spark.sql.sources.DataSourceRegister: com.google.cloud.spark.bigquery.BigQueryRelationProvider not a subtype
  at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:593)
  at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1244)
  at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1273)
  at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1309)
  at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1393)
  at scala.collection.convert.JavaCollectionWrappers$JIteratorWrapper.hasNext(JavaCollectionWrappers.scala:46)
  at scala.collection.StrictOptimizedIterableOps.filterImpl(StrictOptimizedIterableOps.scala:225)
  at scala.collection.StrictOptimizedIterableOps.filterImpl$(StrictOptimizedIterableOps.scala:222)
  at scala.collection.convert.JavaCollectionWrappers$JIterableWrapper.filterImpl(JavaCollectionWrappers.scala:83)
  at scala.collection.StrictOptimizedIterableOps.filter(StrictOptimizedIterableOps.scala:218)
  at scala.collection.StrictOptimizedIterableOps.filter$(StrictOptimizedIterableOps.scala:218)
  at scala.collection.convert.JavaCollectionWrappers$JIterableWrapper.filter(JavaCollectionWrappers.scala:83)
  at org.apache.spark.sql.execution.datasources.DataSource$.lookupDataSource(DataSource.scala:629)
  at org.apache.spark.sql.execution.datasources.DataSource$.lookupDataSourceV2(DataSource.scala:697)
  at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:208)
  at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:172)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.base/java.lang.reflect.Method.invoke(Method.java:569)
  at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
  at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
  at py4j.Gateway.invoke(Gateway.java:282)
  at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
  at py4j.commands.CallCommand.execute(CallCommand.java:79)
  at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
  at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
  at java.base/java.lang.Thread.run(Thread.java:840)`

Thanks!

**Comment by bujiazhang** [comment]
Fixed the dataproc job failed to run issue by specifying the dataproc runtime_config version. The Dataproc job failed because of a most recent version of Dataproc was called when running the n3c_spark_extractor.py script, but the newer version doesn’t work for pyspark process. I had to specify the dataproc runtimeconfig version by adding the following two lines after line 146:
  batch.runtime_config = dataproc_v1.RuntimeConfig()
  batch.runtime_config.version = ‘2.0.80’
The version can be any version that works for you.
